parserOptions:
  ecmaVersion: 2018
  sourceType: 'module'
env:
  es6: true
  browser: true
  commonjs: true
  mocha: true
rules:
  no-undef: 'off'
  no-unused-expressions: 'off'

extends: 'htmlacademy/es6'
