export const SETTINGS = {
  DEBUG: true,
  MAX_FAST_TIME: 10,
  MAX_LEVELS: 10,
  MAX_LIVES: 3,
  MIN_SLOW_TIME: 20,
  NUMBER_OF_ANSWERS: 10,
  SCORE_CORRECT: 100,
  SCORE_FAST: 50,
  SCORE_LIFE: 50,
  SCORE_SLOW: -50,
};
